name = "aifurniture"
compatibility_date = "2026-05-20"
pages_build_output_dir = "dist"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "furproject-db"
database_id = "507651c1-c120-431c-8a6f-10a2a26ecbc2"

[vars]
STORE_NAME = "ABC Luxury Furniture"
CURRENCY = "VND"
ENVIRONMENT = "production"
